using System.Xml.Linq;

namespace USPS.AddressApi.Models
{
    /// <summary>
    /// Represents an error returned from the USPS Address Api.
    ///  Note: This type can be present at the response and item-result level.
    /// </summary>
    public class AddressApiError
    {
        /// <summary>
        /// The error number generated by the USPS Web Tools server.
        /// </summary>
        public string Number { get; set; }

        /// <summary>
        /// A human-readable detailed description of the error.
        /// </summary>
        public string Description { get; set; }
        
        /// <summary>
        /// The component and interface that generated the error on the USPS Web Tools server.
        /// </summary>
        public string Source { get; set; }

        /// <summary>
        /// Creates a new instance of an AddressApiError.
        /// </summary>
        public AddressApiError() { } 
        
        internal AddressApiError(XElement element)
        {
            Number = element.Element(nameof(Number))?.Value;
            Description = element.Element(nameof(Description))?.Value;
            Source = element.Element(nameof(Source))?.Value;
        }

        internal static bool TryParse(XElement element, out AddressApiError error)
        {
            if(element?.Name == Constants.ERROR_ELEMENT_NAME)
            {
                error =  new AddressApiError(element);
                return true;
            }
            else if(element?.Element(Constants.ERROR_ELEMENT_NAME) != null)
            {
                error =  new AddressApiError(element.Element(Constants.ERROR_ELEMENT_NAME));
                return true;
            }
            else
            {
                error = null;
                return false;
            }
        }
    }
}